spring:
  datasource:
    url: jdbc:mysql://192.168.119.11:3306/hiot_thing?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowMultiQueries=true&serverTimezone=GMT
    username: root
    password: Hiot@2019
server:
  port: 9090
mybatis:
  mapperLocations: classpath*:/mapper/*.xml
